seed: 0
wandb_project: PROJECT_NAME
wandb_entity: ENTITY_NAME

save_dir: ./checkpoints
data_dir: ./data


# checkpoint
resume_checkpoint: False
checkpoint_path: None
eval_every_n_epoch: 10

# dataset 
dataset: mnist
is_image: True
in_channels: 1
out_channels: 1
height: 28
width: 28


# monte carlo samples
elbo_mc_samples_eval: 1
elbo_offset_train: 1
elbo_mc_samples_train: 1
elbo_offset_eval: True
hutch_mc: 10

# sde 
sde_type: malda
n_vars: 3
stationary_aux_var: 1.0
init_aux_var: 0.01
stationary_x_var: 1.0
d_full: False

# beta's for SDE 
beta_0: 0.1
beta_1: 10
beta_fn_type: inhom

# score_model type
score_parameterization: noise_pred
score_model_type: TinyUNet
dropout: 0.0

# data transform 
transform: logit

# batch size
batch_size: 128
test_batch_size: 128
accumulate_grad_batches: 1


# optimization
n_epochs: 300
lr: 0.0002
lr_scheduling: False
lr_sched_max_iters: 50000
grad_clip_val: 2.
optim_type: adam
warmup_iters: 5000
weight_decay: 0.0
use_ema: False
ema_decay: 0.9999

# objectives
val_loss_type: dsm_elbo
train_loss_type: dsm_elbo
imp_weight_train: True
switch_epoch: -1

# fid
val_fid_epoch: 400
fid_n_samples: 50000

# diffusion
hybrid_transition_kernel: True

T_max: 1.0                                                                                                                                                       
T_min_sampling: 0.001
T_min_eval: 0.001
T_min_train: 0.001

# sampling params
log_image_step: 50
log_image_size: 8
n_FEs: 500
sampling_method: EM
sampling_t_arr_fn: quadratic

